[package]
name = "pastebin-nickel"
version = "0.1.0"
authors = ["Oliver Jensen <ojensen5115@gmail.com>"]

[dependencies]
nickel = "0.9.0"

hyper = "*"
formdata = "0.11.0"

rand = "0.3.15"
syntect = "1.0.3"
rust-crypto = "^0.2"
lazy_static = "0.2.2"
chrono = "*"